name: Deploy Stage

on:
  push:
    branches:
      - stage

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      # [共用 env]
      AWS_REGION: ap-southeast-1 # AWS Region

      # [storybook env]
      STORYBOOK_OUTPUT_PATH: packages/ui/storybook-static # storybook build output path
      S3_BUCKET_STORYBOOK: siyamap-ui-stage # 用來存 static 的 S3 bucket

      # [NextJS env]
      NEXTJS_STATIC_OUTPUT_PATH: apps/web/.next/static # Next.js static output path
      NEXTJS_PUBLIC_PATH: apps/web/public # Next.js public output path
      S3_BUCKET_NEXTJS_STATIC: siyamap-static-stage # 用來存 Next.js 靜態資產的 S3 bucket
      LAMBDA_NAME_NEXTJS_SSR: siyamap-lambda-stage # Lambda function name
      ECR_REPOSITORY: siyamap/nextjs
      IMAGE_TAG: ${{ github.sha }}

    steps:
      # [START] 共同建置與部署流程
      - name: 1. 拉 repo
        uses: actions/checkout@v4

      - name: 2. 固定 Node 版本
        uses: actions/setup-node@v4
        with:
          node-version: 20
        env:
          PNPM_STORE_PATH: ~/.pnpm-store

      - uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: 3. 安裝依賴
        run: pnpm install --frozen-lockfile

      - name: 4. Build 所有 package
        run: pnpm -r build

      - name: 5. 設定 AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      # [START] 部署 Storybook
      - name: 6-1. 上傳 storybook 到 S3
        run: |
          aws s3 sync ${{ env.STORYBOOK_OUTPUT_PATH }}/ s3://${{ env.S3_BUCKET_STORYBOOK }} \
            --delete \
            --cache-control "no-cache"

      - name: 6-2. 清除 Storybook CloudFront cache
        if: success()
        run: |
          aws cloudfront create-invalidation \
            --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID_STAGE_UI }} \
            --paths "/index.html" "/iframe.html"

      - name: 6-3. 部署 storybook 到 chromatic
        uses: chromaui/action@latest
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN_STAGE }}

      # [START] 部署 Next.js
      - name: 7-1. 登入 Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2
        id: login-ecr

      - name: 7-2. Build and push Docker image for Lambda
        run: |
          cd apps/web
          # 強制停用 BuildKit 的進階 Manifest 功能
          export DOCKER_BUILDKIT=0
          docker build \
            --platform linux/amd64 \
            -t ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }} .

          docker push ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }}

      - name: 7-3. 更新 Lambda function 使用新的 Image
        run: |
          aws lambda update-function-code \
            --function-name ${{ env.LAMBDA_NAME_NEXTJS_SSR }} \
            --image-uri ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }}

          aws lambda wait function-updated --function-name ${{ env.LAMBDA_NAME_NEXTJS_SSR }}

      - name: 7-4. 更新 S3 上的 Next.js 靜態資產
        run: |
          aws s3 sync ${{ env.NEXTJS_STATIC_OUTPUT_PATH }} s3://${{ env.S3_BUCKET_NEXTJS_STATIC }}/_next/static \
            --delete \
            --cache-control "public, max-age=31536000, immutable"

          aws s3 sync ${{ env.NEXTJS_PUBLIC_PATH }} s3://${{ env.S3_BUCKET_NEXTJS_STATIC }}/public \
            --delete \
            --cache-control "public, max-age=3600" # public 檔案通常不帶 Hash，建議快取時間設短一點

      - name: 7-5. 清除 Next.js static CloudFront cache
        if: success()
        run: |
          aws cloudfront create-invalidation \
            --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID_STAGE_STATIC }} \
            --paths "/_next/static/*"
